"""correções nas relações das tabelas

Revision ID: 4111dc5524bf
Revises: d5bd09f21efc
Create Date: 2024-12-29 11:47:24.478859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4111dc5524bf'
down_revision: Union[str, None] = 'd5bd09f21efc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
