"""correções nas relações das tabelas

Revision ID: 91e2b398a4c4
Revises: 4111dc5524bf
Create Date: 2024-12-29 11:55:00.877917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e2b398a4c4'
down_revision: Union[str, None] = '4111dc5524bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
