"""correções nas relações das tabelas

Revision ID: d5bd09f21efc
Revises: 3969b7c57cd4
Create Date: 2024-12-29 11:13:02.827536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5bd09f21efc'
down_revision: Union[str, None] = '3969b7c57cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
